name: pysnowpark
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - defaults
dependencies:
  - python=3.8
  - pyarrow==8.0.0
  - snowflake-snowpark-python
  - pandas
  - numpy
  - seaborn
  - boto3
  - torchvision
  - pip
  - pip:
    - snowflake-cli-labs
    - jupyterlab
    - tqdm

