[geo-playground]
user = "<snowflake_username>"
password = "<snowflake_password>"
account = "<snowflake_account>"
warehouse = "<warehouse_name>"
database = "<database_name>"
schema = "<schema_name>"

[geo-demos]
user = "<snowflake_username>"
password = "<snowflake_password>"
account = "<snowflake_account>"
warehouse = "<warehouse_name>"
database = "<database_name>"
schema = "<schema_name>"