# Note: If you're using a Mac with the M1 chip, 
# please set your CONDA_SUBDIR to osx-arm like so before creating the environment:
# CONDA_SUBDIR=osx-arm64 conda env create -f conda_env.yml
name: snowpark-pandas
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.9
  - jupyter
  - pip
  - pip:
    - "./snowflake_snowpark_python-1.15.0a1-py3-none-any.whl[modin]"