boosting=gbdt
objective=binary
metric=binary_logloss,auc
tree_learner=data
pre_partition=true
header=false
label_column=0
num_leaves=31
learning_rate=0.05
feature_fraction=0.9
bagging_fraction=0.9
bagging_freq=1
verbosity=1
