name: iceberg-cortex-demo
channels:
  - conda-forge
dependencies:
  - findspark=2.0.1
  - jupyter=1.0.0
  - pyspark=3.5.0
  - openjdk=11.0.13
  - python=3.11.6
  - python-dotenv
  - snowflake-snowpark-python
