USE ROLE <% ctx.env.finops_db_admin_role%>;
USE DATABASE <% ctx.env.finops_acct_db %>;
USE SCHEMA <% ctx.env.finops_acct_schema %>;
CREATE OR REPLACE VIEW ORG_QUERY_ACCELERATION_CC_CREDITS_DAY COMMENT = 'Title: Query Acceleration Service (QAS) by Cost Center per day. Description: Analyze query acceleration service costs by cost center per day.'
AS
SELECT
   DATE_TRUNC('DAY', SF.ADJUSTED_START_TIME) AS DAY,
   GET_TAG_COST_CENTER(SF.QUERY_TAG, SF.USER_NAME, TU.TAG_VALUE, SF.ROLE_NAME, TR.TAG_VALUE, TS.TAG_VALUE, TW.TAG_VALUE) AS COST_CENTER,
   ZEROIFNULL(ROUND(SUM(ALLOCATED_CREDITS_USED_QAS), 2)) AS "QAS_COST_CREDITS"  -- Total Query Acceleration Service cost in respective CREDITS for this day.
FROM SF_CREDITS_BY_QUERY_ORG SF -- Generated by cost per query procedure
LEFT JOIN SNOWFLAKE.ORGANIZATION_USAGE.TAG_REFERENCES TR
  ON TR.OBJECT_NAME = SF.ROLE_NAME
    AND TR.ACCOUNT_LOCATOR = SF.ACCOUNT_LOCATOR
    AND TR.TAG_NAME = '<% ctx.env.finops_tag_name %>'
    AND TR.DOMAIN = 'ROLE'
    AND SF.USER_NAME <> 'SYSTEM' -- Exclude Tasks that will be attributed to schema instead of Access Roles that are not tagged.
--Schema Snowflake Tasks
LEFT JOIN SNOWFLAKE.ORGANIZATION_USAGE.TAG_REFERENCES TS
  ON TS.OBJECT_DATABASE = SF.DATABASE_NAME
    AND TS.ACCOUNT_LOCATOR = SF.ACCOUNT_LOCATOR
    AND TS.OBJECT_NAME = SF.SCHEMA_NAME
    AND TS.TAG_NAME = '<% ctx.env.finops_tag_name %>'
    AND TS.DOMAIN = 'SCHEMA'
    AND SF.USER_NAME = 'SYSTEM'
--User overrides
LEFT JOIN SNOWFLAKE.ORGANIZATION_USAGE.TAG_REFERENCES TU
  ON TU.OBJECT_NAME = SF.USER_NAME
    AND TU.ACCOUNT_LOCATOR = SF.ACCOUNT_LOCATOR
    AND TU.TAG_NAME = '<% ctx.env.finops_tag_name %>'
    AND TU.DOMAIN = 'USER'
--Warehouse fallback if nothing else tagged.
LEFT JOIN SNOWFLAKE.ORGANIZATION_USAGE.TAG_REFERENCES TW
  ON TW.OBJECT_NAME = SF.WAREHOUSE_NAME
    AND TW.ACCOUNT_LOCATOR = SF.ACCOUNT_LOCATOR
    AND TW.TAG_NAME = '<% ctx.env.finops_tag_name %>'
    AND TW.DOMAIN = 'WAREHOUSE'
GROUP BY ALL
;

